### ISSUE TITLE
Issue during install - install failed

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [BricksMental/smirnybot9001#17]
This is a bug report .  Unfortunately I do not have the text of the errors,  but simply some screenshots.

Hopefully these are sufficient to investigate the issue.

System:  Windows 11
Python version:  3.12

2 pics showing the initial error experienced during a new install of the bot.

![image](https://github.com/BricksMental/smirnybot9001/assets/51089832/69cb7993-c6e9-4180-98cd-04512ed70d93)

![image](https://github.com/BricksMental/smirnybot9001/assets/51089832/73297dd9-6c11-420a-b84b-c2624bd511cb)

**Comment by BricksMental** [comment]
It looks like at the time you tried to install with Python 3.12 no binary wheel was available for a dependency, lxml. It is now provided upstream, so installation went fine for me with Python 3.12
If something like this happens in the future you have multiple alternatives to waiting for upstream:
a) install Microsoft Visual Studio, so that the wheel can be built locally
b) Use the Option "--prefer-binary" to the pip install command, this will force to use older but available binary wheels instead of attempting to rebuild the wheel
c) Use and older Python version, 3.12 is bleeding edge, for now I'd stick to the stable releases
